tmem: Add src_addr permission check in tmemClose()
switchbrew/libnx pull request #606
Opened 2023-04-02 23:43 UTC by masagrator

When TransferMemory has different permission than RW, we need to check if `src_addr` permission was restored to original state as we currently don't have any assurance this happens at the moment `__libnx_free` is called.

This is fixing an issue with Tesla overlays crashing randomly (mainly in docked mode).

Thanks to `~SciresM` for providing an idea to solve this and `~HE` from ReSwitched for help with shaping out code.

2023-04-13 20:06 UTC, fincs commented
Since this is a bug caused by a race condition in nvservices, it seems a bad idea to special case the workaround in tmemClose. An alternative solution would be to introduce a new `tmemWaitForPermission` function that would wait for a given tmem object to match the specified permission mask/value (as parameters); and use that in nv.c just before calling tmemClose.

2023-04-13 21:52 UTC, masagrator commented
This cannot be done before tmemUnmap is used, otherwise it will stuck in infinite loop.

My proposition is introducing `tmemWaitForPermissionAndClose` that would do what currently my PR is doing, but as separate function.

2023-04-13 21:59 UTC, masagrator commented
Then maybe it's a handle that must be closed first? If not, then I have no idea why it's not working.

My fork I was testing
https://github.com/switchbrew/libnx/compare/master...masagrator:libnx:patch-2

2023-04-13 22:13 UTC, yellows8 commented
Impl the `tmemWaitForPermissionAndClose` you mentioned.

`Then maybe it's a handle that must be closed first? If not, then I have no idea why it's not working.` <- The handle must be closed for that to do anything.

2023-04-13 22:36 UTC, yellows8 commented
Actually you can keep tmemWaitForPermission if tmemCloseHandle is added. tmemCloseHandle would have the handle-closing code from tmemClose, and you'd call this following the _nvCmdInitialize call.

2023-04-14 07:13 UTC, masagrator commented
Checked this in overlays with 2 people and it works fine.
I guess this will need grammar fixes as I'm not great at this.

2023-04-14 14:10 UTC, yellows8 commented
Replace the duplicate code in tmemClose with a call to tmemCloseHandle.

2023-04-14 14:51 UTC, yellows8 requested changes

2023-04-14 14:51 UTC, yellows8 commented on nx/include/switch/kernel/tmem.h
> +
Remove extra newline.

2023-04-14 14:51 UTC, yellows8 commented on nx/include/switch/kernel/tmem.h
> +
Remove extra newline.

2023-04-14 14:51 UTC, yellows8 commented on nx/source/services/nv.c
> +        if (R_SUCCEEDED(rc))
This has to be unconditional. Something like: `Result rc2 = tmemCloseHandle(...);` `if (R_SUCCEEDED(rc)) rc = rc2;`

2023-04-14 15:22 UTC, yellows8 approved these changes

2023-04-14 16:31 UTC, fincs approved these changes

2023-04-14 16:33 UTC, merged

2023-05-27 18:36 UTC, masagrator commented
If such hang happens, you should attach GDB to it and check if it's not stuck in loop. For example in tmemWaitForPermission().
But if this is true, then it would mean that without this function your app would crash with 0x2A8 error code.

2023-05-27 20:34 UTC, masagrator commented
I'm not sure if only RW or RW and R since this is something platform specific. 

You can try to write Perm_R instead of Perm_Rw and see what will happen, it should catch any Read permission.